default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  template: template0

development:
  <<: *default
  database: talking_development

test:
  <<: *default
  database: talking_test

production:
  <<: *default
  database: talking_production
  username: talking
  password: <%= ENV['TALKING_DATABASE_PASSWORD'] %>
